### ISSUE TITLE
Example call?

### ISSUE THREAD

**Issue by thorsten-gehrig** [vojnovski/alexavv#1]
Hi
i´m searching for a longtime for a capability to start/stop my alexa and controll the volume.
Looks like you archived this goal - but i´m not clear how to use this.

I´m guessing capture the coockies, id´s, etc. is not the biggest issue (but guidance would be welcome)... for me it´s more the general topic how to initiate this script.
Is is possible to trigger it from a local (linux) PC as part of my home automation?
Or does Lamda needs to be involved (i have no clue about lamda stuff...)

Kind regards
Thorsten (Thorsten@Gehrig.info)

**Comment by vojnovski** [comment]
HI Thorsten. I am not sure whether this still works, it was done a while ago, and Alexa's api has always been in a state of flux.

In the case that it still does, yes, you can trigger it from wherever that has a recent python installed (your local PC included, as long as it has an outbound internet route).
